# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

APP_STORE_CONNECT_TEAM_ID =       ENV["APP_STORE_CONNECT_TEAM_ID"]      # the team ID of your App Store Connect account
APPLE_ISSUER_ID =                 ENV["APPLE_ISSUER_ID"]                # App Store Connect API Key 🔺Issuer ID
APPLE_KEY_CONTENT =               ENV["APPLE_KEY_CONTENT"]              # App Store Connect API Key 🔺 Key file or Key content of .p8, check it out here: https://github.com/fastlane/fastlane/issues/18655#issuecomment-881764901
APPLE_KEY_ID =                    ENV["APPLE_KEY_ID"]                   # App Store Connect API Key 🔺Key ID
DEVELOPER_APP_ID =                ENV["DEVELOPER_APP_ID"]               # in App Store Connect, go to the app -> App Information -> Scroll down to the General Information section of your app and look for Apple ID.
DEVELOPER_APP_IDENTIFIER =        ENV["DEVELOPER_APP_IDENTIFIER"]       # your app’s bundle identifier
DEVELOPER_PORTAL_TEAM_ID =        ENV["DEVELOPER_PORTAL_TEAM_ID"]       # the ID of your Developer Portal team if you’re in multiple teams
FASTLANE_APPLE_ID =               ENV["FASTLANE_APPLE_ID"]              # your Apple ID username (usually your email address)
GIT_AUTHORIZATION =               ENV["GIT_AUTHORIZATION"]              # <YOUR_GITUSERNAME>:<YOUR_PERSONAL_ACCESS_TOKEN>, eg. joshuadeguzman:mysecretkeyyoudontwanttoknow
MATCH_PASSWORD =                  ENV["MATCH_PASSWORD"]                 # the passphrase that you assigned when initializing match, will be used for decrypting the certificates and provisioning profiles
PROVISIONING_PROFILE_SPECIFIER =  ENV["PROVISIONING_PROFILE_SPECIFIER"] # match AppStore <YOUR_APP_BUNDLE_IDENTIFIER>, eg. match AppStore com.domain.blabla.demo.
TEMP_KEYCHAIN_PASSWORD =          ENV["TEMP_KEYCHAIN_PASSWORD"]         # the password of the temporary keychain
TEMP_KEYCHAIN_USER =              ENV["TEMP_KEYCHAIN_USER"]             # the name of the temporary keychain

def delete_temp_keychain(name)
  delete_keychain(
    name: name
  ) if File.exist? File.expand_path("~/Library/Keychains/#{name}-db")
end

def create_temp_keychain(name, password)
  create_keychain(
    name: name,
    password: password,
    default_keychain: true,
    unlock: true,
    timeout: 3600,
    lock_when_sleeps: false
  )
end

def ensure_temp_keychain(name, password)
  delete_temp_keychain(name)
  create_temp_keychain(name, password)
end

def disable_auto_code_signing(profile)
  update_code_signing_settings(
      use_automatic_signing: false,
      team_id: DEVELOPER_PORTAL_TEAM_ID,
      targets: ["TemplateApp"],
      build_configurations: ["Release"],
      code_sign_identity: "iPhone Distribution",
      profile_name: profile
    )
end

platform :ios do
  desc "Setup keychain"
  lane :setup_keychain do
    keychain_name = TEMP_KEYCHAIN_USER
    keychain_password = TEMP_KEYCHAIN_PASSWORD
    ensure_temp_keychain(keychain_name, keychain_password)
  end

  desc "Fetch certificates and provisioning profiles"
  lane :fetch_certificates do
    api_key = app_store_connect_api_key(
      key_id: APPLE_KEY_ID,
      issuer_id: APPLE_ISSUER_ID,
      key_content: APPLE_KEY_CONTENT,          
      is_key_content_base64: true,  
      duration: 1200,
    )
  
    increment_build_number({
      build_number: latest_testflight_build_number + 1
    })

    sync_code_signing(
      # readonly: true,
      type: "appstore",
      git_basic_authorization: Base64.strict_encode64(GIT_AUTHORIZATION),
      keychain_name: TEMP_KEYCHAIN_USER,
      keychain_password: TEMP_KEYCHAIN_PASSWORD,
      shallow_clone: true,
      ignore_profiles_with_different_name: false 
    )

    sh('security find-certificate -a')
    
=begin
    match(
      type: 'appstore',
      app_identifier: "#{DEVELOPER_APP_IDENTIFIER}",
      git_basic_authorization: Base64.strict_encode64(GIT_AUTHORIZATION),
      readonly: true,
      keychain_name: TEMP_KEYCHAIN_USER,
      keychain_password: TEMP_KEYCHAIN_PASSWORD,
      api_key: api_key
    )
=end
  end

  lane :prebuild do
    profile = ENV["sigh_#{DEVELOPER_APP_IDENTIFIER}_appstore_profile-name"]
  
    disable_auto_code_signing(profile)
  end 

  lane :build do
    profile = ENV["sigh_#{DEVELOPER_APP_IDENTIFIER}_appstore_profile-name"]

    build_app(
      scheme: "TemplateApp",
      export_method: "app-store",
      # export_options: {
      #   provisioningProfiles: { 
      #       DEVELOPER_APP_ID => profile
      #   }
      # }
    )
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    setup_keychain
    fetch_certificates
    # prebuild
    build

    upload_to_app_store(
      precheck_include_in_app_purchases: false
    )

    delete_temp_keychain(TEMP_KEYCHAIN_USER)
  end

  desc "Push a new release build to the App Store"
  lane :release do
    snapshot
    increment_build_number(xcodeproj: "TemplateApp.xcodeproj")
    match(type: "appstore")
    build_app(scheme: "TemplateApp")
    upload_to_app_store(
      
    )
  end
end
