devices([
     "iPad Pro (12.9-inch) (6th generation)",
    #  "iPad mini (6th generation)",
     "iPhone 8 Plus",
     "iPhone 13 mini",
     "iPhone 14",
     "iPhone 14 Plus",
     "iPhone SE (3rd generation)"
])

clear_previous_screenshots(true)
override_status_bar(true)
dark_mode(true)
erase_simulator(true)
concurrent_simulators(true)
app_identifier(ENV["DEVELOPER_APP_IDENTIFIER"])