devices([
    "iPhone 14 Pro Max",
    "iPhone 8",
    "iPhone 8 Plus",
    "iPad Pro (11-inch) (4th generation)",
    "iPad Pro (12.9-inch) (6th generation)",
])

clear_previous_screenshots(true)
override_status_bar(true)
dark_mode(true)
# erase_simulator(true)
# concurrent_simulators(true)
app_identifier(ENV["DEVELOPER_APP_IDENTIFIER"])