name: Manual Deployment
on:
  push:
    branches: [ manual_build ]

  workflow_dispatch:

jobs:
  deploy:
    name: Manual iOS Build and Deploy
    runs-on: macOS-latest
    
    steps:
      - name: Select Xcode 
        run: sudo xcode-select -switch /Applications/Xcode_14.2.app
      - name: Xcode version
        run: /usr/bin/xcodebuild -version
      - name: Show Dinectory Content
        run: ls -la
      # - name: Build archive 
      #   run: |
      #     xcodebuild -sdk iphoneos -project TemplateApp.xcodeproj \
      #       -configuration Release -scheme CocoaHeadsL\
      #       -derivedDataPath DerivedData \
      #       -archivePath DerivedData/Archive/CocoaHeadsNL archive
      # - name: Export Archive 
      #   run: |
      #     xcodebuild -exportArchive
      #       -archivePath DerivedData/Archive/CocoaHeadsL.carchive |
      #       -exportOptionsPlist provisioning/App-Store.plist \
      #       -exportPath DerivedData/ipa