name: Manual Deployment (Self-Hosted)
on:
  push:
    branches: [ manual_build ]

  workflow_dispatch:
  

jobs:
  deploy:
    name: Manual iOS Build and Deploy
    runs-on: self-hosted
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Xcode version
        run: /usr/bin/xcodebuild -version

      - name: Show Dinectory Content
        run: ls -la

      - name: Setup Keychain
        run: |
          chmod +x ci/install_certificates_and_profiles.sh
          ci/install_certificates_and_profiles.sh
        env:
          TEMP_KEYCHAIN_USER: ${{ secrets.TEMP_KEYCHAIN_USER }}
          TEMP_KEYCHAIN_PASSWORD: '${{ secrets.TEMP_KEYCHAIN_PASSWORD }}'
          SIGN_CER_BASE64: ${{ secrets.SIGN_CER_BASE64 }}
          SIGN_KEY_BASE64: ${{ secrets.SIGN_KEY_BASE64 }}
          SIGN_PROV_PROFILE_BASE64: ${{ secrets.SIGN_PROV_PROFILE_BASE64 }}
          APPLE_CERT_G3: ${{ secrets.APPLE_CERT_G3 }}

      - name: Build archive 
        run: |
          xcodebuild -sdk iphoneos -project TemplateApp.xcodeproj \
            -configuration Release -scheme TemplateApp\
            -derivedDataPath DerivedData \
            -archivePath DerivedData/Archive/TemplateApp archive

      - name: Export Archive 
        run: |
          xcodebuild -exportArchive -archivePath DerivedData/Archive/TemplateApp.xcarchive -exportOptionsPlist ci/ExportOptions.plist -exportPath DerivedData/ipa

      # - name: Deploy App to Apple
      #   run: |
      #     xcrun altool --upload-app --type ios \
      #       -file DerivedData/ipa/CocoaHeadsNLipa|
      #       --username "${{ secrets.appstore_connect_username 72" |
      #       --password "${{ secrets.appstore_connect_password }}"
      #       --verbose