name: System Name
on:
  # push:
  #   branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions a tab
  workflow_dispatch:

jobs:
  deploy:
    name: Print system name
    runs-on: macOS-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Deploy iOS Beta to TestFlight via Fastlane
        uses: maierj/fastlane-action@v1.4.0
        with:
          lane: print_system_name
